[package]
name = "da-csound"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
da-interface = { path = "../da-interface" }
csound = "0.1.8"