[package]
name = "da-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jack = "0.11.4"
jack-sys = "0.5.1"
libloading = "0.8.1"
da-interface = { path = "../da-interface" }